"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {useParams} from "next/navigation";
type Person={name:string;email:string};type Exchange={name:string;organizer:string;budget:string;date:string;people:Person[];code:string};
export default function ExchangePage(){const {code}=useParams<{code:string}>();const [x,setX]=useState<Exchange|null>(null);const [assignments,setAssignments]=useState<Record<string,string>>({});const [selected,setSelected]=useState("");const [revealed,setRevealed]=useState(false);
useEffect(()=>{const raw=localStorage.getItem("gift-exchange-"+code);if(raw)setX(JSON.parse(raw))},[code]);
function draw(){if(!x)return;let recipients=[...x.people.map(p=>p.name)];for(let tries=0;tries<500;tries++){recipients=[...recipients].sort(()=>Math.random()-.5);if(x.people.every((p,i)=>p.name!==recipients[i])){const a:Record<string,string>={};x.people.forEach((p,i)=>a[p.name]=recipients[i]);setAssignments(a);setRevealed(false);return}}}
if(!x)return <main className="formPage"><div className="formShell"><Link className="brand" href="/">Gift<span>Exchange</span></Link><h1>Exchange<br/><em>not found.</em></h1></div></main>;
return <main><nav className="nav shell"><Link className="brand" href="/">Gift<span>Exchange</span></Link><span className="codePill">{x.code}</span></nav><section className="dashboard shell"><p className="sectionLabel">YOUR EXCHANGE</p><h1>{x.name}</h1><div className="exchangeMeta"><span><b>{"$"+x.budget}</b> budget</span><span><b>{x.date||"TBD"}</b> gift date</span><span><b>{x.people.length}</b> people</span></div><div className="dashboardGrid"><section className="panel"><p className="sectionLabel">PARTICIPANTS</p>{x.people.map(p=><div className="participant" key={p.name}><span className="avatar">{p.name[0].toUpperCase()}</span><div><b>{p.name}</b><small>{p.email||"Ready to draw"}</small></div><span className="check">✓</span></div>)}</section><section className="panel drawPanel"><p className="sectionLabel">PRIVATE DRAW</p><h2>{Object.keys(assignments).length?"Assignments ready.":"Ready to draw names?"}</h2><p>Everyone gets exactly one person, and nobody can draw themselves.</p>{!Object.keys(assignments).length?<button className="button" onClick={draw}>Draw names <span>✦</span></button>:<><label>Preview as<select value={selected} onChange={e=>{setSelected(e.target.value);setRevealed(false)}}><option value="">Choose participant</option>{x.people.map(p=><option key={p.name}>{p.name}</option>)}</select></label>{selected&&(!revealed?<button className="revealButton" onClick={()=>setRevealed(true)}>Tap to reveal</button>:<div className="revealCard"><small>{selected.toUpperCase()}, YOU&apos;RE GIFTING</small><strong>{assignments[selected]}</strong><span>Keep it secret. Make it good.</span></div>)}</>}</section></div></section></main>}